// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using LearnTsinghua.Models;

namespace LearnTsinghua.iOS
{
    public partial class CourseCell : UITableViewCell
    {
        public CourseCell(IntPtr handle)
            : base(handle)
        {
        }

        public void Populate(Course course)
        {
            TitleLabel.Text = course.Name;
            TitleLabel.TextColor = course.NoMaterials() ? UIColor.LightGray : UIColor.DarkTextColor;
                        
            LocationLabel.Text = course.Location();
            TimeLabel.Text = course.TimeString();
        }
    }
}
