// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using LearnTsinghua.Models;

namespace LearnTsinghua.iOS
{
    public partial class CourseDoneAssignmentCell : UITableViewCell
    {
        public CourseDoneAssignmentCell(IntPtr handle)
            : base(handle)
        {
        }

        public void Populate(Assignment assignment)
        {
            TitleLabel.Text = assignment.Title;

            string mark = null;
            if (assignment.Submission?.MarkedAt != DateTime.MinValue)
            {
                mark = assignment.Submission.Mark == null ? "已阅" : assignment.Submission.Mark.ToString();
            }
            MarkLabel.Text = mark;
        }
    }
}
