// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using LearnTsinghua.Extensions;
using LearnTsinghua.Models;

namespace LearnTsinghua.iOS
{
    public partial class CourseFileCell : UITableViewCell
    {
        public CourseFileCell(IntPtr handle)
            : base(handle)
        {
        }

        public void Populate(File file)
        {
            if (file != null)
            {
                TitleLabel.Text = file.Title;
                DescriptionLabel.Text = file.Description.Oneliner();
                SubtitleLabel.Text = string.Format("{0}，{1}", file.CreatedAt.DaysSince(), file.SizeString());
            }
        }
    }
}
