// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using LearnTsinghua.Extensions;
using LearnTsinghua.Models;

namespace LearnTsinghua.iOS
{
    public partial class CourseAnnouncementCell : UITableViewCell
    {
        public CourseAnnouncementCell(IntPtr handle)
            : base(handle)
        {
        }

        public void Populate(Announcement annc)
        {
            if (annc != null)
            {
                Title.Text = annc.Title;
                CreatedAt.Text = annc.CreatedAt.DaysSince();
                Detail.Text = annc.BodyText().Oneliner();
            }
        }
    }
}
