// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LearnTsinghua.iOS
{
	public partial class CourseAssignmentCell : UITableViewCell
	{
		public CourseAssignmentCell (IntPtr handle) : base (handle)
		{
		}
	}
}
