// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using LearnTsinghua.Models;

namespace LearnTsinghua.iOS
{
    public partial class FileController : UIViewController
    {
        public File File { get; set; }

        public FileController(IntPtr handle)
            : base(handle)
        {
        }
    }
}
