// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;

using Foundation;
using UIKit;

using LearnTsinghua.Extensions;
using LearnTsinghua.Models;

namespace LearnTsinghua.iOS
{
    public partial class SemesterController : UITableViewController
    {
        public string SelectedSemesterId { get; set; }

        public SemesterController(IntPtr handle)
            : base(handle)
        {
        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            TableView.Source = new SemesterSource(SelectedSemesterId);
            TableView.ReloadData();
        }

        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {
            if (segue.Identifier == "UnwindToCourseListController")
            {
                var source = TableView.Source as SemesterSource;
                SelectedSemesterId = source.GetSemesterId(TableView.IndexPathForSelectedRow);
            }
        }
    }

    public class SemesterSource : UITableViewSource
    {
        const string cellIdentifier = "SemesterCell";

        string currentSemesterId;
        string selectedSemesterId;
        Dictionary<string, List<string>> semesterIds;
        List<string> years;

        public SemesterSource(string selectedSemesterId)
        {
            currentSemesterId = Semester.Get().Id;
            this.selectedSemesterId = selectedSemesterId;

            semesterIds = new Dictionary<string, List<string>>();
            years = new List<string>();

            var attendedIds = Me.Get().AttendedIds;
            var ids = new List<string>(attendedIds.Keys);
            ids.Sort((lhs, rhs) => rhs.CompareTo(lhs));

            foreach (var id in ids)
            {
                var courseCount = attendedIds[id].Count;

                string year, semester;
                id.ParseSemesterId(out year, out semester);

                if (!semesterIds.ContainsKey(year))
                {
                    semesterIds[year] = new List<string>();
                    years.Add(year);
                }

                semesterIds[year].Add(id);
            }
        }

        public override nint NumberOfSections(UITableView tableView)
        {
            return years.Count;
        }

        public override nint RowsInSection(UITableView tableview, nint section)
        {
            return semesterIds[years[(int)section]].Count;
        }

        public override string TitleForHeader(UITableView tableView, nint section)
        {
            return years[(int)section];
        }

        public string GetSemesterId(NSIndexPath indexPath)
        {
            return semesterIds[years[indexPath.Section]][indexPath.Row];
        }

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var id = GetSemesterId(indexPath);
            string year, semester;
            id.ParseSemesterId(out year, out semester);

            var cell = tableView.DequeueReusableCell(cellIdentifier);
            cell.TextLabel.Text = semester;
            
            if (id == currentSemesterId)
                cell.TextLabel.Text = cell.TextLabel.Text + "（当前学期）";
            if (id == selectedSemesterId)
            {
                cell.TextLabel.Highlighted = true;
                cell.Accessory = UITableViewCellAccessory.Checkmark;
            }
            else
            {
                cell.TextLabel.Highlighted = false;
                cell.Accessory = UITableViewCellAccessory.None;
            }
            return cell;
        }
    }
}
